[theme]
base = "dark"
backgroundColor = "#050a0e"
secondaryBackgroundColor = "#090f15"
primaryColor = "#f97316"
textColor = "#e8f4f2"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
